# Generated by Django 4.2 on 2024-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline_to",
            field=models.DateField(default=None, null=True),
        ),
    ]
